version: '3.8'

services:
  # FastAPI backend service
  fastapi:
    build:
      context: ./src/services/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/trained/house_price_prediction.pkl
      - PREPROCESSOR_PATH=/app/models/trained/preprocessor.pkl
    volumes:
      - ./models/trained:/app/models/trained
    networks:
      - mlops-network
    restart: unless-stopped

  # Streamlit frontend service
  streamlit:
    build:
      context: ./src/services/ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
      - APP_VERSION=1.0.0
    depends_on:
      - fastapi
    networks:
      - mlops-network
    restart: unless-stopped

  # Metabase BI service
  metabase:
    build:
      context: ./deployment/metabase
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
      - JAVA_OPTS=-Xmx2g
    volumes:
      - /home/wsl/dev/mlops/fullstack-mlops/deployment/metabase/data:/metabase-data
      - /home/wsl/dev/mlops/fullstack-mlops/deployment/metabase/plugins:/plugins
      - /home/wsl/dev/mlops/fullstack-mlops/src/ml/data/dwh/data:/app/data
    networks:
      - mlops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mlops-network:
    driver: bridge 