# Ensemble model configuration for house price prediction using DuckDB
ensemble:
  name: "house_price_ensemble_duckdb"
  target_variable: "price"
  method: "stacking"  # voting, stacking, blending
  voting_method: "soft"  # soft, hard (for voting ensemble)
  
# Base models configuration
base_models:
  RandomForest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    n_jobs: -1
    weight: 0.3
    
  XGBoost:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    n_jobs: -1
    weight: 0.4
    
  GradientBoosting:
    n_estimators: 150
    max_depth: 5
    learning_rate: 0.05
    subsample: 0.8
    random_state: 42
    weight: 0.3

# Stacking configuration (if method is stacking)
stacking:
  meta_model: "LinearRegression"
  cv_folds: 5
  use_probas: false

# Training configuration
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  cross_validation: true

# Model evaluation
evaluation:
  metrics:
    - "mae"
    - "r2"
    - "rmse"
  threshold:
    r2_min: 0.7
    mae_max: 100000 