# モデル訓練設定
training:
  # データ分割設定
  test_size: 0.2
  random_state: 42
  shuffle: true
  
  # 交差検証設定
  cv_folds: 5
  cv_scoring: "neg_mean_absolute_error"
  
  # ハイパーパラメータ最適化
  n_trials: 100
  timeout: 300
  
  # モデル保存設定
  save_model: true
  save_preprocessor: true
  save_metadata: true
  
  # 評価メトリクス
  metrics:
    - "mae"
    - "mse"
    - "rmse"
    - "r2"
    - "mape"
  
  # ログ設定
  verbose: true
  log_level: "INFO"
  
  # 並列処理設定
  n_jobs: -1
  
  # メモリ効率設定
  memory_efficient: false
